# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.10.100"
  # config.hostsupdater.aliases = ["development.local"]

  # Synce the app folder (not copying in. it's synching)

  # config.vm.synced_folder "path/origin/folder", "path/to/destination/folder"
  config.vm.synced_folder "app", "/app"

  # run the provision script making sure you're in the correct path
  config.vm.provision "shell", path: "environment/provision.sh"
end